version: '3'

services:
  backend:
    image: dungnt07/web_project_backend
    ports:
      - 3001:3001
    env_file:
      - backend.env
    
  frontend:
    image: dungnt07/web_project_frontend
    ports:
      - 5173:5173
    env_file:
      - frontend.env
    depends_on:
      - backend

  admin-panel:
    image: dungnt07/web_project_admin
    ports:
      - 4000:4000
    env_file:
      - admin.env
    depends_on:
      - backend
