name: Build and Publish

on:
  push:
    branches:
      - "develop"
      - "main"
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web_project_backend:latest
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web_project_frontend:latest
      - name: Build and push admin-panel image
        uses: docker/build-push-action@v2
        with:
          context: ./admin-panel
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web_project_admin:latest

  pull-and-up:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env file from secrets
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > frontend.env
          echo "${{ secrets.BACKEND_ENV }}" > backend.env
          echo "${{ secrets.ADMIN_ENV }}" > admin.env
      - name: Copy frontend.env
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "frontend.env"
          target: ${{ secrets.PATH }}
      - name: Copy backend.env
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "backend.env"
          target: ${{ secrets.PATH }}
      - name: Copy admin.env
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "admin.env"
          target: ${{ secrets.PATH }}
      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: ${{ secrets.PATH }}
      - uses: appleboy/ssh-action@master
        name: Pull new image and rerun with the new version
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PATH }}
            docker compose pull && docker compose down && docker compose up -d
