name: Build and Publish

on:
  push:
    branches:
      - "develop"
      - "main"
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: { { secrets.DOCKERHUB_USERNAME } }
          password: { { secrets.DOCKERHUB_ACCESS_TOKEN } }
      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: dungnt07/web_project_backend:latest
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: dungnt07/web_project_frontend:latest
      - name: Build and push admin-panel image
        uses: docker/build-push-action@v2
        with:
          context: ./admin-panel
          push: true
          tags: dungnt07/web_project_admin:latest
